services:
  tavily-mcp:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: mcp_tavily_server
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
      - TAVILY_API_KEY=${TAVILY_API_KEY:-}
    env_file:
      - ../.env
    command: ["src.mcp_servers.tavily_search.server:create_app", "--host", "0.0.0.0", "--port", "3000", "--factory", "--workers", "1"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - mcp_network

networks:
  mcp_network:
    driver: bridge